__title__ = 'etg'
__description__ = 'ETG API v3 Python SDK'
__url__ = ''
__version__ = '0.8.0'
__author__ = 'Sergey Popinevskiy'
__author_email__ = 'sergey.popinevskiy@gmail.com'
__license__ = 'MIT'
__copyright__ = 'Copyright 2020 Sergey Popinevskiy'
